name: split_up
description: Simplify shared expenses effortlessly with intuitive tracking and smart splitting

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
